ci:
  autofix_prs: false

exclude: |
    (?x)^(
        versioneer\.py|
        pytensor/_version\.py|
        doc/.*|
    )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: debug-statements
        exclude: |
          (?x)^(
              pytensor/breakpoint\.py|
              pytensor/graph/op\.py|
              pytensor/compile/nanguardmode\.py|
              pytensor/graph/rewriting/basic\.py|
              pytensor/tensor/variable\.py|
          )$
      - id: check-merge-conflict
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: ["--fix", "--output-format=full"]
      - id: ruff-format
