exclude: |
    (?x)^(
        versioneer\.py|
        pytensor/_version\.py|
        doc/.*|
        bin/.*
    )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: debug-statements
        exclude: |
          (?x)^(
              pytensor/breakpoint\.py|
              pytensor/graph/op\.py|
              pytensor/compile/nanguardmode\.py|
              pytensor/graph/rewriting/basic\.py|
              pytensor/tensor/var\.py|
          )$
      - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        exclude: |
          (?x)^(
              .*/?__init__\.py|
              pytensor/graph/toolbox\.py|
              pytensor/link/jax/jax_dispatch\.py|
              pytensor/link/jax/jax_linker\.py|
              pytensor/scalar/basic_scipy\.py|
              pytensor/tensor/linalg\.py
          )$
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        additional_dependencies:
        - numpy>=1.20
        - types-filelock
        - types-setuptools
