# To use:
#
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate pytensor-dev
#
name: pytensor-dev
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - compilers
  - numpy>=1.17.0
  - scipy>=0.14
  - filelock
  - etuples
  - logical-unification
  - miniKanren
  - cons
  - pydeprecate
  # Intel BLAS
  - mkl
  - mkl-service
  - libblas=*=*mkl
  # numba backend
  - numba>=0.57
  # For testing
  - coveralls
  - diff-cover
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-benchmark
  - pytest-mock
  # For building docs
  - sphinx>=5.1.0,<6
  - sphinx_rtd_theme
  - pygments
  - pydot
  - ipython
  # code style
  - ruff
  # developer tools
  - pre-commit
  - packaging
  - typing_extensions
  # optional
  - cython
  - graphviz
  - pydot
