name: pytensor-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - gcc_linux-64
  - gxx_linux-64
  - numpy
  - scipy
  - six
  - sphinx>=5.1.0,<6
  - mock
  - pillow
  - pymc-sphinx-theme
  - sphinx-design
  - pygments
  - pydot
  - ipython
  - myst-nb
  - matplotlib
  - watermark
  - ablog
  - pip
  - pip:
    - sphinx_sitemap
    - -e ..
